# Generated by Django 5.2 on 2025-04-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ashes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Imię i nazwisko')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numer telefonu')),
                ('subject', models.CharField(choices=[('pokaz', 'Zapytanie o pokaz'), ('warsztaty', 'Zapytanie o warsztaty'), ('współpraca', 'Propozycja współpracy'), ('inne', 'Inne')], max_length=20, verbose_name='Temat')),
                ('message', models.TextField(verbose_name='Wiadomość')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
            ],
            options={
                'verbose_name': 'Wiadomość kontaktowa',
                'verbose_name_plural': 'Wiadomości kontaktowe',
                'ordering': ['-created_at'],
            },
        ),
    ]
