# Generated by Django 5.2 on 2025-05-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Data')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść cytatu')),
                ('reflection', models.TextField(verbose_name='Refleksja')),
                ('is_published', models.BooleanField(default=True, verbose_name='Opublikowany')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cytat',
                'verbose_name_plural': 'Cytaty',
                'ordering': ['date'],
            },
        ),
    ]
