# Generated by Django 5.2 on 2025-05-05 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailystoic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adres email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywny')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subskrybent newslettera',
                'verbose_name_plural': 'Subskrybenci newslettera',
            },
        ),
    ]
